export const timeZones = [
  { id: "America/Adak", name: "America/Adak (-09:00)" },
  { id: "America/Anchorage", name: "America/Anchorage (-08:00)" },
  { id: "America/Anguilla", name: "America/Anguilla (-04:00)" },
  { id: "America/Antigua", name: "America/Antigua (-04:00)" },
  { id: "America/Araguaina", name: "America/Araguaina (-03:00)" },
  {
    id: "America/Argentina/Catamarca",
    name: "America/Argentina/Catamarca (-03:00)",
  },
  {
    id: "America/Argentina/Buenos_Aires",
    name: "America/Argentina/Buenos_Aires (-03:00)",
  },
  {
    id: "America/Argentina/ComodRivadavia",
    name: "America/Argentina/ComodRivadavia (-03:00)",
  },
  {
    id: "America/Argentina/Cordoba",
    name: "America/Argentina/Cordoba (-03:00)",
  },
  { id: "America/Argentina/Jujuy", name: "America/Argentina/Jujuy (-03:00)" },
  {
    id: "America/Argentina/La_Rioja",
    name: "America/Argentina/La_Rioja (-03:00)",
  },
  {
    id: "America/Argentina/Mendoza",
    name: "America/Argentina/Mendoza (-03:00)",
  },
  {
    id: "America/Argentina/Rio_Gallegos",
    name: "America/Argentina/Rio_Gallegos (-03:00)",
  },
  { id: "America/Argentina/Salta", name: "America/Argentina/Salta (-03:00)" },
  {
    id: "America/Argentina/San_Juan",
    name: "America/Argentina/San_Juan (-03:00)",
  },
  {
    id: "America/Argentina/San_Luis",
    name: "America/Argentina/San_Luis (-03:00)",
  },
  {
    id: "America/Argentina/Tucuman",
    name: "America/Argentina/Tucuman (-03:00)",
  },
  {
    id: "America/Argentina/Ushuaia",
    name: "America/Argentina/Ushuaia (-03:00)",
  },
  { id: "America/Aruba", name: "America/Aruba (-04:00)" },
  { id: "America/Asuncion", name: "America/Asuncion (-04:00)" },
  { id: "America/Atikokan", name: "America/Atikokan (-05:00)" },
  { id: "America/Atka", name: "America/Atka (-09:00)" },
  { id: "America/Bahia", name: "America/Bahia (-03:00)" },
  { id: "America/Bahia_Banderas", name: "America/Bahia_Banderas (-05:00)" },
  { id: "America/Barbados", name: "America/Barbados (-04:00)" },
  { id: "America/Belem", name: "America/Belem (-03:00)" },
  { id: "America/Belize", name: "America/Belize (-06:00)" },
  { id: "America/Blanc-Sablon", name: "America/Blanc-Sablon (-04:00)" },
  { id: "America/Boa_Vista", name: "America/Boa_Vista (-04:00)" },
  { id: "America/Bogota", name: "America/Bogota (-05:00)" },
  { id: "America/Boise", name: "America/Boise (-06:00)" },
  { id: "America/Buenos_Aires", name: "America/Buenos_Aires (-03:00)" },
  { id: "America/Cambridge_Bay", name: "America/Cambridge_Bay (-06:00)" },
  { id: "America/Campo_Grande", name: "America/Campo_Grande (-04:00)" },
  { id: "America/Cancun", name: "America/Cancun (-05:00)" },
  { id: "America/Caracas", name: "America/Caracas (-04:00)" },
  { id: "America/Catamarca", name: "America/Catamarca (-03:00)" },
  { id: "America/Cayenne", name: "America/Cayenne (-03:00)" },
  { id: "America/Cayman", name: "America/Cayman (-05:00)" },
  { id: "America/Chicago", name: "America/Chicago (-05:00)" },
  { id: "America/Chihuahua", name: "America/Chihuahua (-06:00)" },
  { id: "America/Coral_Harbour", name: "America/Coral_Harbour (-05:00)" },
  { id: "America/Cordoba", name: "America/Cordoba (-03:00)" },
  { id: "America/Costa_Rica", name: "America/Costa_Rica (-06:00)" },
  { id: "America/Creston", name: "America/Creston (-07:00)" },
  { id: "America/Cuiaba", name: "America/Cuiaba (-04:00)" },
  { id: "America/Curacao", name: "America/Curacao (-04:00)" },
  { id: "America/Danmarkshavn", name: "America/Danmarkshavn (+00:00)" },
  { id: "America/Dawson", name: "America/Dawson (-07:00)" },
  { id: "America/Dawson_Creek", name: "America/Dawson_Creek (-07:00)" },
  { id: "America/Denver", name: "America/Denver (-06:00)" },
  { id: "America/Detroit", name: "America/Detroit (-04:00)" },
  { id: "America/Dominica", name: "America/Dominica (-04:00)" },
  { id: "America/Edmonton", name: "America/Edmonton (-06:00)" },
  { id: "America/Eirunepe", name: "America/Eirunepe (-05:00)" },
  { id: "America/El_Salvador", name: "America/El_Salvador (-06:00)" },
  { id: "America/Ensenada", name: "America/Ensenada (-07:00)" },
  { id: "America/Fort_Nelson", name: "America/Fort_Nelson (-07:00)" },
  { id: "America/Fort_Wayne", name: "America/Fort_Wayne (-04:00)" },
  { id: "America/Fortaleza", name: "America/Fortaleza (-03:00)" },
  { id: "America/Glace_Bay", name: "America/Glace_Bay (-03:00)" },
  { id: "America/Godthab", name: "America/Godthab (-02:00)" },
  { id: "America/Goose_Bay", name: "America/Goose_Bay (-03:00)" },
  { id: "America/Grand_Turk", name: "America/Grand_Turk (-04:00)" },
  { id: "America/Grenada", name: "America/Grenada (-04:00)" },
  { id: "America/Guadeloupe", name: "America/Guadeloupe (-04:00)" },
  { id: "America/Guatemala", name: "America/Guatemala (-06:00)" },
  { id: "America/Guayaquil", name: "America/Guayaquil (-05:00)" },
  { id: "America/Guyana", name: "America/Guyana (-04:00)" },
  { id: "America/Halifax", name: "America/Halifax (-03:00)" },
  { id: "America/Havana", name: "America/Havana (-04:00)" },
  { id: "America/Hermosillo", name: "America/Hermosillo (-07:00)" },
  {
    id: "America/Indiana/Indianapolis",
    name: "America/Indiana/Indianapolis (-04:00)",
  },
  { id: "America/Indiana/Knox", name: "America/Indiana/Knox (-05:00)" },
  { id: "America/Indiana/Marengo", name: "America/Indiana/Marengo (-04:00)" },
  {
    id: "America/Indiana/Petersburg",
    name: "America/Indiana/Petersburg (-04:00)",
  },
  {
    id: "America/Indiana/Tell_City",
    name: "America/Indiana/Tell_City (-05:00)",
  },
  { id: "America/Indiana/Vevay", name: "America/Indiana/Vevay (-04:00)" },
  {
    id: "America/Indiana/Vincennes",
    name: "America/Indiana/Vincennes (-04:00)",
  },
  { id: "America/Indiana/Winamac", name: "America/Indiana/Winamac (-04:00)" },
  { id: "America/Indianapolis", name: "America/Indianapolis (-04:00)" },
  { id: "America/Inuvik", name: "America/Inuvik (-06:00)" },
  { id: "America/Iqaluit", name: "America/Iqaluit (-04:00)" },
  { id: "America/Jamaica", name: "America/Jamaica (-05:00)" },
  { id: "America/Jujuy", name: "America/Jujuy (-03:00)" },
  { id: "America/Juneau", name: "America/Juneau (-08:00)" },
  {
    id: "America/Kentucky/Louisville",
    name: "America/Kentucky/Louisville (-04:00)",
  },
  {
    id: "America/Kentucky/Monticello",
    name: "America/Kentucky/Monticello (-04:00)",
  },
  { id: "America/Knox_IN", name: "America/Knox_IN (-05:00)" },
  { id: "America/Kralendijk", name: "America/Kralendijk (-04:00)" },
  { id: "America/La_Paz", name: "America/La_Paz (-04:00)" },
  { id: "America/Lima", name: "America/Lima (-05:00)" },
  { id: "America/Los_Angeles", name: "America/Los_Angeles (-07:00)" },
  { id: "America/Louisville", name: "America/Louisville (-04:00)" },
  { id: "America/Lower_Princes", name: "America/Lower_Princes (-04:00)" },
  { id: "America/Maceio", name: "America/Maceio (-03:00)" },
  { id: "America/Managua", name: "America/Managua (-06:00)" },
  { id: "America/Manaus", name: "America/Manaus (-04:00)" },
  { id: "America/Marigot", name: "America/Marigot (-04:00)" },
  { id: "America/Martinique", name: "America/Martinique (-04:00)" },
  { id: "America/Matamoros", name: "America/Matamoros (-05:00)" },
  { id: "America/Mazatlan", name: "America/Mazatlan (-06:00)" },
  { id: "America/Mendoza", name: "America/Mendoza (-03:00)" },
  { id: "America/Menominee", name: "America/Menominee (-05:00)" },
  { id: "America/Merida", name: "America/Merida (-05:00)" },
  { id: "America/Metlakatla", name: "America/Metlakatla (-08:00)" },
  { id: "America/Mexico_City", name: "America/Mexico_City (-05:00)" },
  { id: "America/Miquelon", name: "America/Miquelon (-02:00)" },
  { id: "America/Moncton", name: "America/Moncton (-03:00)" },
  { id: "America/Monterrey", name: "America/Monterrey (-05:00)" },
  { id: "America/Montevideo", name: "America/Montevideo (-03:00)" },
  { id: "America/Montreal", name: "America/Montreal (-04:00)" },
  { id: "America/Montserrat", name: "America/Montserrat (-04:00)" },
  { id: "America/Nassau", name: "America/Nassau (-04:00)" },
  { id: "America/New_York", name: "America/New_York (-04:00)" },
  { id: "America/Nipigon", name: "America/Nipigon (-04:00)" },
  { id: "America/Nome", name: "America/Nome (-08:00)" },
  { id: "America/Noronha", name: "America/Noronha (-02:00)" },
  {
    id: "America/North_Dakota/Beulah",
    name: "America/North_Dakota/Beulah (-05:00)",
  },
  {
    id: "America/North_Dakota/Center",
    name: "America/North_Dakota/Center (-05:00)",
  },
  {
    id: "America/North_Dakota/New_Salem",
    name: "America/North_Dakota/New_Salem (-05:00)",
  },
  { id: "America/Nuuk", name: "America/Nuuk (-02:00)" },
  { id: "America/Ojinaga", name: "America/Ojinaga (-06:00)" },
  { id: "America/Panama", name: "America/Panama (-05:00)" },
  { id: "America/Pangnirtung", name: "America/Pangnirtung (-04:00)" },
  { id: "America/Paramaribo", name: "America/Paramaribo (-03:00)" },
  { id: "America/Phoenix", name: "America/Phoenix (-07:00)" },
  { id: "America/Port-au-Prince", name: "America/Port-au-Prince (-04:00)" },
  { id: "America/Port_of_Spain", name: "America/Port_of_Spain (-04:00)" },
  { id: "America/Porto_Acre", name: "America/Porto_Acre (-05:00)" },
  { id: "America/Porto_Velho", name: "America/Porto_Velho (-04:00)" },
  { id: "America/Puerto_Rico", name: "America/Puerto_Rico (-04:00)" },
  { id: "America/Punta_Arenas", name: "America/Punta_Arenas (-03:00)" },
  { id: "America/Rainy_River", name: "America/Rainy_River (-05:00)" },
  { id: "America/Rankin_Inlet", name: "America/Rankin_Inlet (-05:00)" },
  { id: "America/Recife", name: "America/Recife (-03:00)" },
  { id: "America/Regina", name: "America/Regina (-06:00)" },
  { id: "America/Resolute", name: "America/Resolute (-05:00)" },
  { id: "America/Rio_Branco", name: "America/Rio_Branco (-05:00)" },
  { id: "America/Rosario", name: "America/Rosario (-03:00)" },
  { id: "America/Santa_Isabel", name: "America/Santa_Isabel (-07:00)" },
  { id: "America/Santarem", name: "America/Santarem (-03:00)" },
  { id: "America/Santiago", name: "America/Santiago (-04:00)" },
  { id: "America/Santo_Domingo", name: "America/Santo_Domingo (-04:00)" },
  { id: "America/Sao_Paulo", name: "America/Sao_Paulo (-03:00)" },
  { id: "America/Scoresbysund", name: "America/Scoresbysund (+00:00)" },
  { id: "America/Shiprock", name: "America/Shiprock (-06:00)" },
  { id: "America/Sitka", name: "America/Sitka (-08:00)" },
  { id: "America/St_Barthelemy", name: "America/St_Barthelemy (-04:00)" },
  { id: "America/St_Johns", name: "America/St_Johns (-02:30)" },
  { id: "America/St_Kitts", name: "America/St_Kitts (-04:00)" },
  { id: "America/St_Lucia", name: "America/St_Lucia (-04:00)" },
  { id: "America/St_Thomas", name: "America/St_Thomas (-04:00)" },
  { id: "America/St_Vincent", name: "America/St_Vincent (-04:00)" },
  { id: "America/Swift_Current", name: "America/Swift_Current (-06:00)" },
  { id: "America/Tegucigalpa", name: "America/Tegucigalpa (-06:00)" },
  { id: "America/Thule", name: "America/Thule (-03:00)" },
  { id: "America/Thunder_Bay", name: "America/Thunder_Bay (-04:00)" },
  { id: "America/Tijuana", name: "America/Tijuana (-07:00)" },
  { id: "America/Toronto", name: "America/Toronto (-04:00)" },
  { id: "America/Tortola", name: "America/Tortola (-04:00)" },
  { id: "America/Vancouver", name: "America/Vancouver (-07:00)" },
  { id: "America/Virgin", name: "America/Virgin (-04:00)" },
  { id: "America/Whitehorse", name: "America/Whitehorse (-07:00)" },
  { id: "America/Winnipeg", name: "America/Winnipeg (-05:00)" },
  { id: "America/Yakutat", name: "America/Yakutat (-08:00)" },
  { id: "America/Yellowknife", name: "America/Yellowknife (-06:00)" },
];
